name: Go Build and Release
permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.9" # Specify your Go version
          cache: true # Enable built-in Go caching

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -o ai

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./ai
          draft: false
          prerelease: false
          generate_release_notes: true
